dist: trusty
sudo: required
language: bash
env:
  global:
    PACKER_VERSION: '1.4.4'
    TERRAFORM_VERSION: '0.12.8'
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh | bash

install:
  # Install Hashicorp's packer
  - |
    curl -L -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    unzip -d ~/bin packer.zip
    packer version  
  # Install terraform
  - |
    curl -L -o terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
    unzip -d ~/bin terraform.zip
    terraform --version
  # install ansible linter
  - |
    pip install --user ansible-lint
    ansible-lint --version
    # Install tflint
  - |
    curl https://raw.githubusercontent.com/wata727/tflint/master/install_linux.sh | bash
    tflint --version

script:
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - packer validate -var-file=./packer/variables.json.example ./packer/app.json
  - cd terraform/prod && terraform get && cd ../..
  - cd terraform/prod && terraform init -backend=false && cd ../..
  - cd terraform/prod && terraform validate && cd ../..
  - cd terraform/stage && terraform get && cd ../..
  - cd terraform/stage && terraform init -backend=false && cd ../..
  - cd terraform/stage && terraform validate && cd ../..
  - tflint terraform/prod
  - tflint terraform/stage
  - ansible-lint -v ansible/playbooks/site.yml

notifications:
  slack:
    rooms:
      secure: TRH99JXW8g2kTd/7Ky3OpDXSKxc1vAbfQ3RRv8NL9w3Db88sAzBJutsTI+E2Zl4puht0JUNWhixXOeaAOvGzgUKihHTG1OetIvbgB0nmCwn1N9NEW8yMcZyS5oLo7K73pSTIRTTs0rlOXHOi+0altvkTCyKc5R+cAlFq1+5C5QbtOk/wRcnwT9zY9D7+BvJtAeCbQONosuxTsdD4LnYHlOTorre/YOV84JuRouH1+Plt/ZWWm2GCWxw/prpXAvEXf3W+7Xg97nruobtIFSst6fF//e+x6ecI1RMXq8P0fQopExrLUeF+rpo329dnvqf24VEZPSIdERGKneTY/+uCLi9OxhEN98pEtMrR8sZD9XHsZ/jKlha5j+CmebwOZZSM3/U1ilfaML/es/y5VI+zGDLqe9d/FSu1tAUo7GagJlg1E43dFPjsiwPj7Sa0BtKcmgMbYjGFMTruPTfJ5N327VEddmdLlt6/5uZahIXYuN0Vi9J8hrc+noEtyaHm/E875of0VNL5oBma2pzn46Ueg9zBvpySd0i2Z57KBlIKVdWx4AKrJ9qFm+zEkRt3EDK2HdBRRxMAq6EQst5NRAXYIAX+SOZcS+IblfR9dBbAa9K1KCUBIZaRff1jaIYQzGjM5P493ErEN8WH9AFlqxvNFlJQJZLXSMgMxywyxnEMFCo=
