{
  "os": "linux",
  "dist": "trusty",
  "sudo": "required",
  "group": "stable",
  ".result": "configured",
  "language": "bash",
  "before_install": [
    "curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh | bash"
  ]
}
