  - name: Add APT key
    apt_key:
      id: D68FA50FEA312927
      keyserver: keyserver.ubuntu.com
    tags: install

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
    tags: install

  # Выполняем установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      force_apt_get: yes
      state: present
    tags: install

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
      state: started
    tags: install
