---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
   msg: "This host in {{env}} environment!!!"

- include: ruby.yml
  tags:
   - ruby_app

- include: puma.yml
  tags:
   - puma_app