---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  # Добавляем ключ репозитория
  - name: Add APT key
    apt_key:
      id: D68FA50FEA312927
      keyserver: keyserver.ubuntu.com

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  # Выполняем установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      force_apt_get: yes
      state: present

  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
      notify: restart mongod

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
